### ISSUE TITLE
Does CSG support planes?

### ISSUE THREAD

**Issue by amengpp** [manthrax/THREE-CSGMesh#16]
I use a "planes" to interact with a "box", but it return wrong geometry. Does the CSG support planes like mesh, not a solid mesh.

**Comment by amengpp** [comment]
My task is to do csg between two gltf model, but the model has more than two materials. the three gltf loader will split the model to more than one mesh which is not solid.

**Comment by amengpp** [comment]
![image](https://user-images.githubusercontent.com/10844202/141114668-d582fa6c-70ff-42e0-b159-5ecbc371ecb5.png)
mesh "1" and "2", do interact, the mesh "3" is the wrong result.

**Comment by sonygod** [comment]
https://github.com/Jiro-Digital/three-csg-ts/issues/45

**Comment by manthrax** [comment]
This won't work the way you are hoping. A square/quad plane will act like a box of infinite depth. To get the effect that you want, I suggest taking the resulting cube geometry, and do your own processing on it to remove all the faces but the top faces. You can determine which of the faces is are top faces, by looking at the vertex normals for each face.

**Comment by manthrax** [comment]
Short answer No.. The library doesn't work that way, and what you are calling a "plane" is not actually a true plane in the geometry sense, it's a coplanar triangulated quad. And a non volumetric object consisting of some co-planar polygons will extend off to infinity on the back side, which is why you see the result of your cube being chopped out of the plane. You can post process your geometry to remove the faces that you don't want though.
