### ISSUE TITLE
ConeGeometry / LatheGeometry incorrect result

### ISSUE THREAD

**Issue by AsDeadAsADodo** [manthrax/THREE-CSGMesh#24]
[intersecting a box with a cone results in a slice of the surface of the cone instead of a solid object](https://github.com/manthrax/THREE-CSGMesh/issues/10)
I did not test cone , only test LatheGeometry.
```
CSG.toMesh(
    CSG.fromMesh(A).intersect(CSG.fromMesh(B)),
    A.matrix,
    A.material
 );
```
[giladdarshan](https://github.com/giladdarshan) suggest change [Line #73](https://github.com/manthrax/THREE-CSGMesh/blob/master/three-csg.js#L73) to
```
return CSG.fromPolygons(polys.filter(p=>!isNaN(p.plane.normal.x)));
```
This issue still exists , subtract and union both return partial of the LatheGeometry , intersect returns something close to A-B but not exactly A-B

**Comment by manthrax** [comment]
Cones sometimes have many points condensed down into a single degenerate face or multiple degenerate faces. 
The  : return CSG.fromPolygons(polys.filter(p=>!isNaN(p.plane.normal.x)));
fix attempts to check for that.. but you can also get around it by using a cone that doesn't have a degenerate face cap.

Did you try it with the fix?

I'm always on the fence about adding checks like this since it's technically a data problem.. and the check incurs a penalty on a heavy objects. If you test it, and it solves your issue.. I will make a greater effort to include it.
